version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: tests
          command: npm test
      - deploy:
          name: pm2 deploy
          command: ./node_modules/.bin/pm2 deploy staging
